### ISSUE TITLE
translated files are overridden

### ISSUE THREAD

**Issue by maddy2101** [ayacoo/xliff#9]
When using the translate command and a file already exists, it is adjusted and in this process, already existing translations are overriden. See here:
![xliff_translate](https://user-images.githubusercontent.com/1925287/168012857-e750d0e9-9291-42d9-9254-d11c0bcd36ba.png)

**Comment by ayacoo** [comment]
@maddy2101 I would just always exclude that now, or is there a need here to control something like that with a command option?

**Comment by maddy2101** [comment]
sure, I will contact you via Email.
My expectation was to add missing entries, but leave the available ones alone.

**Comment by ayacoo** [comment]
Okay, I understand. So far, I have always assumed complete translations.

I'll take care of a PR in a few days. I'm still on holiday at the moment ;-)

**Comment by maddy2101** [comment]
enjoy, there is no hurry from my side. Thanks for all your work.

**Comment by ayacoo** [comment]
Since it is quiet here now, I would close the issue. If something else comes up, feel free to open a new issue :-)
